services:
  - type: web
    name: helnet
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn HELNET.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_E7bHWSMAOV2I@ep-polished-credit-a9sjp92b-pooler.gwc.azure.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHONUNBUFFERED
        value: "1" 